name: faqchatbot
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.10
  - flask=2.2.5
  - numpy=1.26.4
  - pandas=2.2.2
  - scipy=1.13.1
  - scikit-learn=1.5.0
  - spacy=3.7.4
  - nltk=3.8.1
  - gensim=4.3.2
  - tqdm=4.66.4
  - jinja2=3.1.4
  - requests=2.31.0
  - charset-normalizer=3.3.2
  - setuptools=70.0.0
  - wheel=0.43.0
  - pip=24.0
  - blas=1.0=mkl
  - mkl=2024.0.0
  - mkl-service=2.4.1
  - mkl_fft=1.3.8
  - mkl_random=1.3.1
  - joblib=1.4.2
  - ca-certificates
  - openssl
  - certifi
  - cython-blis
  - pathy
  - cymem
  - preshed
  - thinc
  - srsly
  - langcodes
  - wasabi
  - murmurhash
  - catalogue
  - typing_extensions
  - packaging
  - python-dateutil
  - pytz
  - click
  - colorama
  - markupsafe
  - itsdangerous
  - werkzeug
  - regex
  - shellingham
  - urllib3
  - zlib
  - xz
  - tk
  - sqlite
  - fftw
  - bzip2
  - vc
  - vs2015_runtime
  - icc_rt
  - pip:
      - absl-py==2.3.0
      - astunparse==1.6.3
      - bert-serving-client==1.10.0
      - bert-serving-server==1.10.0
      - cachetools==5.3.3
      - en-core-web-sm==3.7.1
      - faiss-cpu==1.11.0
      - flatbuffers==24.3.25
      - gast==0.5.4
      - google-auth==2.29.0
      - google-auth-oauthlib==1.2.0
      - google-pasta==0.2.0
      - gputil==1.4.0
      - grpcio==1.64.0
      - h5py==3.11.0
      - jax==0.4.25
      - keras==3.3.3
      - libclang==18.1.2
      - markdown==3.6
      - ml-dtypes==0.3.2
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - protobuf==5.26.1
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pydantic==2.7.1
      - python-version==0.0.2
      - pyzmq==26.0.3
      - requests-oauthlib==1.4.0
      - rsa==4.9
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.16.1
      - tensorflow-estimator==2.16.1
      - tensorflow-io-gcs-filesystem==0.37.0
      - tensorflow-intel==2.16.1
      - termcolor==2.4.0
      - wrapt==1.16.0
      - langchain==0.3.26
      - openai==1.30.2
      - openapi-schema-pydantic==1.2.4
      - tiktoken==0.7.0
